[package]
name = "debug_test"
version = "0.1.0"
authors = ["thinhvqnguyen <thinhvqnguyen@kobiton.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
